name: kamusi
description: kiswahili kitukuzwe

version: 1.2.7+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animated_floatactionbuttons: ^0.1.0
  async: ^2.4.0
  backdrop: ^0.2.8
  cupertino_icons: ^0.1.2
  english_words: ^3.1.5
  flutter_html : ^1.0.2
  flutter_launcher_icons: ^0.6.1
  flutter_slidable: ^0.5.4
  fluttertoast: ^7.0.2
  http: ^0.12.0
  intl: ^0.15.7
  json_annotation: ^3.0.1
  matrix_gesture_detector: ^0.1.0
  path_provider: ^1.6.11
  percent_indicator: ^2.1.3
  provider: ^4.3.2
  responsive_widgets: ^2.0.1
  share: ^0.6.4+3
  shared_preferences: ^0.5.8
  shared_preferences_settings: ^1.2.0
  swipedetector: ^1.2.0
  sqflite: ^1.3.1
  vertical_tabs: ^0.2.0

flutter_icons:
  image_path: "assets/images/appicon.png"
  android: true
  ios: true

dev_dependencies:
  build_runner: ^1.1.2
  json_serializable: ^3.3.0

  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/kamusi.db
    - assets/images/appicon.png
    - assets/images/appsmata.png
    - assets/images/book.jpg
    - assets/images/bg.jpg
    - assets/images/donation_airtel.png
    - assets/images/donation_equitel.png
    - assets/images/donation_mpesa.png
    - assets/images/donation_paypal.png
    - assets/images/header.png
    - assets/images/ic_arrow_back_white.png
    - assets/images/ic_books.png
    - assets/images/ic_check_circle.png
    - assets/images/ic_done.png
    - assets/images/ic_edit.png
    - assets/images/ic_fab_online.png
    - assets/images/ic_fab_search.png
    - assets/images/ic_favorite_black.png
    - assets/images/ic_favorite_border_black.png
    - assets/images/ic_font_bigger.png
    - assets/images/ic_font_smaller.png
    - assets/images/ic_home.png
    - assets/images/logo.png
    - assets/images/splash.jpg